version: "3"
services:
  backend:
    restart: always
    container_name: TRENDVI-Backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:8000
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:trendvi@redis:6379/0
    volumes:
      - shared_data:/app/output
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    restart: always
    container_name: TRENDVI-Frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - ${VITE_PORT}:80
    depends_on:
      - backend
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [ "celery", "-A", "celery_config.celery_app", "worker", "--loglevel=info" ]
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:trendvi@redis:6379/0
    volumes:
      - shared_data:/app/output
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [ "celery", "-A", "celery_config.celery_app", "beat", "--loglevel=info" ]
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://:trendvi@redis:6379/0
    volumes:
      - shared_data:/app/output
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "", "--stop-writes-on-bgsave-error", "no", "--requirepass", "trendvi" ]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  shared_data: